services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - mongo
      - chroma
    networks:
      - app-network
    restart: unless-stopped

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - app-network
    restart: unless-stopped

  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    volumes:
      - chroma_data:/chroma/chroma
    ports:
      - "8001:8000"
    networks:
      - app-network
    restart: unless-stopped

  chroma-visualizer:
    build:
      context: .
      dockerfile: Dockerfile
    command: python servidor_visualizador.py
    ports:
      - "5000:5000"
    depends_on:
      - chroma
    networks:
      - app-network
    environment:
      - CHROMA_HOST=chroma
      - CHROMA_PORT=8000
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:
  chroma_data:
